### ISSUE TITLE
Training Day 1

### ISSUE THREAD

**Issue by ygm125** [ygm125/Soldier#1]
nothing to do ~

**Comment by wmy19930609** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>

<body>
    <button id="button">click</button>
    <script>
        var E = {
            on: function(dom, evt, fn){
                var evtGroup = evt.split(' ')
                evtGroup.forEach(function(evtItem){
                    if(typeof dom[evtItem] == 'function'){
                        // 原生的方法
                        dom[evtItem + 'IsNative'] = true
                        dom.addEventListener(evt, fn, false)
                        dom[evtItem + 'fn'] = dom[evt + 'fn'] || []
                        dom[evtItem + 'fn'].push(fn)
                    }else{
                        // 自定义事件
                        dom[evtItem + 'IsNative'] = false
                        dom[evtItem] = dom[evtItem] || []
                        dom[evtItem].push(fn)
                    }
                })
            },

            emit: function(dom, evt){
                if(dom[evt]){
                    if(dom[evt + 'IsNative']){
                        dom[evt + 'fn'].forEach(function(evtItem){
                            evtItem()
                        })
                    }else{
                        dom[evt].forEach(function(evtItem){
                            evtItem()
                        })
                    }
                }
            },

            off: function(dom, evt){
                if(dom[evt + 'IsNative']){
                    dom[evt + 'fn'].forEach(function(evtItem){
                        dom.removeEventListener(evt, evtItem, false)
                    })
                }else{
                    delete dom[evt]
                }
                
            }
        }

        var button = document.getElementById('button')
        
        E.on(button, 'click dataclick', function(){
            alert(2)
        })
        E.off(button, 'dataclick')
        E.emit(button, 'dataclick')
        E.emit(button, 'click')
    </script>
</body>

</html>

**Comment by ygm125** [comment]
首先要把实现代码贴出来，可以一眼看到，其次demo的话可以放到链接中

**Comment by wmy19930609** [comment]
var E = {
            on: function(dom, evt, fn){
                var evtGroup = evt.split(' ')
                evtGroup.forEach(function(evtItem){
                    if(typeof dom[evtItem] == 'function'){
                        // 原生的方法
                        dom[evtItem + 'IsNative'] = true
                        dom.addEventListener(evt, fn, false)
                        dom[evtItem + 'fn'] = dom[evt + 'fn'] || []
                        dom[evtItem + 'fn'].push(fn)
                    }else{
                        // 自定义事件
                        dom[evtItem + 'IsNative'] = false
                        dom[evtItem] = dom[evtItem] || []
                        dom[evtItem].push(fn)
                    }
                })
            },

            emit: function(dom, evt){
                if(dom[evt]){
                    if(dom[evt + 'IsNative']){
                        dom[evt + 'fn'].forEach(function(evtItem){
                            evtItem()
                        })
                    }else{
                        dom[evt].forEach(function(evtItem){
                            evtItem()
                        })
                    }
                }
            },

            off: function(dom, evt){
                if(dom[evt + 'IsNative']){
                    dom[evt + 'fn'].forEach(function(evtItem){
                        dom.removeEventListener(evt, evtItem, false)
                    })
                }else{
                    delete dom[evt]
                }
                
            }
        }

        var button = document.getElementById('button')
        
        E.on(button, 'click dataclick', function(){
            alert(2)
        })
        E.off(button, 'dataclick')
        E.emit(button, 'dataclick')
        E.emit(button, 'click')
